language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - openssl aes-256-cbc -K $encrypted_9f360b3d7cd1_key -iv $encrypted_9f360b3d7cd1_iv -in psicashlib/src/main/cpp/psicashlib/SecretTestValues.h.enc -out psicashlib/src/main/cpp/psicashlib/SecretTestValues.h -d
    - pip install --user cpp-coveralls

script: cd psicashlib/src/main/cpp/psicashlib && ./test.sh

after_success:
  - coveralls --root ./build/CMakeFiles/psicash.dir
